# Generated by Django 5.2.6 on 2025-11-14 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_estado_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.municipio', verbose_name='Municipio'),
            preserve_default=False,
        ),
    ]
