# Generated by Django 5.2.6 on 2025-11-28 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_datospersonales_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='rfc',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='ine',
            field=models.CharField(default=1, max_length=18, validators=[django.core.validators.RegexValidator(code='ine_invalido', message='El INE no tiene un formato válido', regex='[BCDFGHJKLMNPQRSTVWXYZ]{6}[0-9]{2}[0-1]{1}[0-9]{1}[0-3]{1}[0-9]{1}[0-3]{1}[0-9]{1}[HM]{1}[0-9]{3}')], verbose_name='INE'),
            preserve_default=False,
        ),
    ]
