# Generated by Django 5.2.6 on 2025-11-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
