# Generated by Django 5.2.6 on 2025-11-27 23:53

import votos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_partido_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=votos.models.candidato_foto_path),
        ),
        migrations.AlterField(
            model_name='partido',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=votos.models.partido_foto_path),
        ),
    ]
