# Generated by Django 5.2.6 on 2025-09-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('stock', models.IntegerField()),
                ('presentacion', models.CharField(choices=[('1', 'Caja'), ('2', 'Pieza'), ('3', 'Paquete')], max_length=1, verbose_name='Presentacizión')),
                ('color', models.CharField(choices=[('1', 'Caja'), ('2', 'Pieza'), ('3', 'Paquete')], max_length=1, verbose_name='Presentacizión')),
            ],
        ),
    ]
