# Generated by Django 5.2.6 on 2025-09-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='color',
            field=models.CharField(choices=[('r', 'Rojo'), ('a', 'Azul'), ('v', 'Verde')], max_length=1),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
