# Generated by Django 5.2.6 on 2025-09-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0002_alter_articulos_color_alter_articulos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='color',
            field=models.CharField(choices=[('r', 'Rojo'), ('a', 'Azul'), ('v', 'Verde')], default='a', max_length=1),
        ),
    ]
