# Generated by Django 5.2.6 on 2025-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
