# Generated by Django 5.2.6 on 2025-10-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_categoria_alter_articulos_stock_articulos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
    ]
