# Generated by Django 5.2.6 on 2025-10-30 19:20

import articulos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=articulos.models.articulo_image_upload_path)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='articulos.articulos')),
            ],
        ),
    ]
